### ISSUE TITLE
Support ES 2018?

### ISSUE THREAD

**Issue by tinchodias** [dorellang/hunter#10]
Only if it's not too difficult. 

This is an example of a game that uses vue.js, where hunter parses >1000 files correctly but errors in 13 because "property spread notation".

https://github.com/HabitRPG/habitica

**Comment by dorellang** [comment]
Unfortunately Esprima doesn't support yet the ES2018 object spread notation in the latest stable release, so I think we're stuck with this for now.

Another option it would be to grab the master version for this, but I don't know how stable it is, so I'd rather leave this closed for now and work on more urgent issues :/
