### ISSUE TITLE
Draw edges behind nodes?

### ISSUE THREAD

**Issue by tinchodias** [dorellang/hunter#13]
Before:
![screenshot from 2018-10-30 12-21-09](https://user-images.githubusercontent.com/3044265/47729404-db4ade00-dc3e-11e8-911e-ab1361a76a37.png)

After:

![screenshot from 2018-10-30 12-23-05](https://user-images.githubusercontent.com/3044265/47729429-e69e0980-dc3e-11e8-8386-7292a2cd3779.png)

---

IMHO, it looks better. This was my change in `HNProject>>#visualizePrograms`:
~~~
	b edges 
		moveBehind;	
		connectToAll: #resolvedDependencies.
~~~

**Comment by tinchodias** [comment]
(the project being visualized is habitica)

**Comment by dorellang** [comment]
Thank you!
This is fixed with https://github.com/dorellang/hunter/commit/28ec67e54a4d08f640dba4a4e942de47a67d117d
