### ISSUE TITLE
External dependencies

### ISSUE THREAD

**Issue by santiago-a-vidal** [dorellang/hunter#14]
It would be great to visualize the external dependencies of an application. In this case I think that we should only show the "direct dependencies" (the ones that you declare in package.json). Then, when you click in an external dependencie's node, the "indrect" dependencies (the ones used by the dependency) should be shown.

**Comment by tinchodias** [comment]
I guess we consider also this issue as out-of-scope for this stage of Hunter.

**Comment by tinchodias** [comment]
The development branch shows the external dependencies. Only one level, not the internal files of the npm dependency. I think we can close this issue.
