### ISSUE TITLE
Errors parsing Habitica

### ISSUE THREAD

**Issue by santiago-a-vidal** [dorellang/hunter#19]
Habitica (https://github.com/HabitRPG/habitica) is one of the largest graph that I could find. But it has some js files that cannot be parsed. Can you checked?

**Comment by dorellang** [comment]
This is happens because of the ES2018 object spread notation that is currently not supported on Esprima, so I think there is not so much to do about it for now.

Related Hunter issue: https://github.com/dorellang/hunter/issues/10
Related Esprima issue: https://github.com/jquery/esprima/issues/1927
