### ISSUE TITLE
Change z-index of edges when highlighted

### ISSUE THREAD

**Issue by tinchodias** [dorellang/hunter#24]
Currently in the Programs visualization, when you hover over the nodes, its edges are highlighted. But it can happen that this edge is is hidden by other edges appear in front of it and thus it can be hard to distinguish, especially very dense graphs. See this image for reference
![screenshot from 2018-11-20 16-29-10](https://user-images.githubusercontent.com/3044265/48797638-805a5300-ece1-11e8-82f2-03798f8fac52.png)

**Comment by tinchodias** [comment]
It should be fixed by latest Roassal2 since last Friday, we should check.

**Comment by tinchodias** [comment]
Not sure it's fixed

**Comment by bergel** [comment]
Yes it is

**Comment by tinchodias** [comment]
I close the issue then
