### ISSUE TITLE
Cannot find module 'esprima-bin-wrapper.node.js'

### ISSUE THREAD

**Issue by xge** [dorellang/hunter#48]
Hi,

while trying to run Hunter I always get the same error message:

````
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'C:\C:\Users\<REDACTED>\Documents\Pharo\images\hunter\pharo-local\iceberg\dorellang\hunter\esprima-bin-wrapper\dist\esprima-bin-wrapper.node.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
````

**Notice the duplicate drive letter in the path: `C:\C:\`**

I'm running a 32bit Image of Pharo 7 on a 64bit Windows 10 Machine. I tried it with several of my own Javascript projects, as well as with [https://github.com/lodash/lodash](https://github.com/lodash/lodash).

I'm not sure if this really is a bug in Hunter or if I just messed up when tried to get it running.

**Comment by tinchodias** [comment]
Hello, thanks for the report. It should be a bug that's not covered by Travis because it run tests only in Linux.

**Comment by xge** [comment]
Do you plan to fix this or have a workaround?

**Comment by tinchodias** [comment]
Yes, definitely we plan to fix it. This week I don't have a Windows computer at hand, but I looked at the code and maybe we can find a workaround for your case.

Could you tell me the results of this expression in a workspace?
~~~
HNEsprimaWrapper baseDirectory pathString
~~~
You can open a workspace with the sequence of `ctrl+o, ctrl+w`.

**Comment by xge** [comment]
The string is: `C:\Users\<REDACTED>\Documents\Pharo\images\hunter\pharo-local\iceberg\dorellang\hunter`

Thanks for your help.

**Comment by tinchodias** [comment]
Thanks. Today I tried to install Hunter on Windows and got an unrelated error (couldn't load a dependency). I'm checking that. Meanwhile, maybe you can tell me two results more so I can guess the problem:
~~~
HNEsprimaWrapper esprimaWrapperPath
~~~
and
~~~
HNEsprimaWrapper esprimaWrapperPath asPath
~~~
and 
~~~
HNEsprimaWrapper esprimaWrapperPath asPath pathString
~~~
Apparently some step in this path construction adds a new `C:\`. (But I don't imagine why it worked on my Windows some months ago.)

Thank you

**Comment by xge** [comment]
Ok, I'm trying to get the formatting right ;)

````Smalltalk
HNEsprimaWrapper esprimaWrapperPath
`````

evaluating this gives me a `FileReference` and it prints the content of the file (truncated output):

````javascript
!function(t){var e={};function n(i){if(e[i])return e[i].exports;var r=e[i]={i:i,l:!1,exports:{}};return t[i].call(r.exports,r,r.exports,n),r.l=!0,r.exports}n.m=t,n.c=e,n.d=function(t,e,i){n.o(t,e)||Object.defineProperty(t,e,{enumerable:!0,get:i})},n.r=function(t){"undefined"!=typeof Symbol&
````

and

````Smalltalk
HNEsprimaWrapper esprimaWrapperPath asPath
````

````Smalltalk
"Path / 'C:' / 'Users' / '<REDACTED>' / 'Documents' / 'Pharo' / 'images' / 'hunter' / 'pharo-local' / 'iceberg' / 'dorellang' / 'hunter' / 'esprima-bin-wrapper' / 'dist' / 'esprima-bin-wrapper.node.js'"
self
````

and

````Smalltalk
HNEsprimaWrapper esprimaWrapperPath asPath pathString
````

````Smalltalk
/C:/Users/<REDACTED>/Documents/Pharo/images/hunter/pharo-local/iceberg/dorellang/hunter/esprima-bin-wrapper/dist/esprima-bin-wrapper.node.js
````

**Comment by tinchodias** [comment]
Thank you very much. I suspect of that first slash (before C:). During next days I will check on my laptop with Windows 10. 

In the case you want to try, this may be a workaround for you (expanding the `<REDACTED>`):
~~~
HNEsprimaWrapper baseDirectory: 'C:\Users\<REDACTED>\Documents\Pharo\images\hunter\pharo-local\iceberg\dorellang\hunter\esprima-bin-wrapper\dist\esprima-bin-wrapper.node.js' asFileReference
~~~

**Comment by tinchodias** [comment]
@xge did you install Hunter using the Metacello way inside Pharo? (or the build.sh script?)

I think I found the problem. In Windows, only tested the build.sh way to install it.

**Comment by xge** [comment]
I used metacello to install Hunter.
Thanks for the workaround. I will try it and report back if it worked!

**Comment by xge** [comment]
I'm sorry, but my Pharo skills are not advanced enough to use the suggested workaround. I tried executing it in a playground, prior to opening a project in Hunter, but to no avail.
As you have already an idea for a fix, I would be ok with closing this issue.

Thanks for your help!

**Comment by tinchodias** [comment]
Finally have a fix.  I have it in a branch for the moment... if you can try it, you can evaluate in a Pharo 7:
```
EpMonitor current disable.
Metacello new
	baseline: 'Hunter';
	repository: 'github://dorellang/hunter:48-Cannot-find-module-esprima-bin-wrappernodejs/src';
	load.
EpMonitor current enable
```

The `EpMonitor current disable.` and enable is to speed up the loading in my laptop with Windows+slow HDD, not a good combination for code loading. (Anyway, it took 24 minutes)

If you don't have the time to try it, I will just merge into master, since it worked here.

**Comment by xge** [comment]
Ok, I can confirm that this branch works. Good job!

**Comment by tinchodias** [comment]
Thanks, I'll merge the pr

**Comment by tinchodias** [comment]
@xge Don't hesitate to contact me if you have some question or comment about the code. It may need some refactorings to make it more comprehensible for new developers.
